### ISSUE TITLE
GO Import broken

### ISSUE THREAD

**Issue by gavmckee80** [k8snetworkplumbingwg/sriovnet#57]
Hi , 

I'm getting the following error when importing the lib
```
go: finding module for package github.com/k8snetworkplumbingwg/sriovnet
go: found github.com/k8snetworkplumbingwg/sriovnet in github.com/k8snetworkplumbingwg/sriovnet v1.1.0
go: github.com/gavmckee80/mlx6 imports
        github.com/k8snetworkplumbingwg/sriovnet: github.com/k8snetworkplumbingwg/sriovnet@v1.1.0: parsing go.mod:
        module declares its path as: github.com/Mellanox/sriovnet
                but was required as: github.com/k8snetworkplumbingwg/sriovnet
```

Can someone advise ?

**Comment by adrianchiris** [comment]
Hi,

we moved this project from Mellanox to k8snetworkplumbingwg. can you try with latest ?
the last release has package referencing the old place, so you can also try to import using the old path "github.com/Mellanox/sriovnet"

in any case i will open an issue to request a new release.
